# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
#
print("Enter limit: ")
limit = gets.to_i

# first, find and store all fibonacci numbers up to and including the limit
# into an array
fib = [1, 2]
while (true)
  number = fib[-2] + fib[-1]
  if (number < limit)
    fib << number
  else
    break
  end
end

# then take the sum of all those fibonacci numbers that are even
sum = 0
fib.each do |elem|
  if (elem % 2 == 0)
    sum += elem
  end
end

puts("TOTAL: #{sum}")
